# Profil local (localhost)

# Wir wollen mehrere Services gleichzeitig laufen lassen. Das geht nur, wenn
# sie auf unterschiedlichen Ports lauschen. Wir starten mal ein 9090, jeder
# weitere Business-Microservice wird einfach um 100 erh√∂ht.
server:
  port: 9090

service-registry:
  server:
    hostname: localhost

# Ususal Spring Boot Configuration
#debug: true

# IntelliJ support ANSI-Colors
spring:
  output:
    ansi:
      enabled: ALWAYS
